trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - template: /templates/tmpl-variables.yml

resources:
  repositories:
    - repository: adoTemplatesAzure
      type: git
      name: Into.Infrastructure/Into.Ado.Templates
      ref: main

stages:
  - template: /templates/tmpl-create-image.yml
    parameters:
      name: BuildDockerImageProductionROW
      display_name: Build Production Image (ROW)
      environment: production
      region: NEU
