trigger:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: adoTemplatesAzure
    type: git
    name: Into.Infrastructure/Into.Ado.Templates
    ref: main

variables:
- template: /templates/template-variables.yml

stages:
  - template: /templates/template-image-create.yml
    parameters:
      name: BuildDockerImageStaging
      display_name: Build Staging Image
      environment: staging
      region: NEU
  - template: /templates/template-image-deploy.yml
    parameters:
      name: DeployToStaging
      display_name: Deploy to Staging
      depends_on: [ BuildDockerImageStaging ] 
      environment: staging
      region: NEU
      manifest_file_name: staging.yml
      image_tag: $(image_tag)
