import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators, FormGroup } from '@angular/forms';
import { NewVoter } from '../model/dtos/new-voter';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.scss']
})
export class AutoGeneratedComponent implements OnInit {
  dealerNotSelected = false;

  registrationForm = this.formBuilder.group({
    name: ['', Validators.required],
    role: ['', Validators.required],
    group: '',
  });

  constructor(
    private formBuilder: FormBuilder,
  ) { }

  ngOnInit() {
  }

  onSubmit(form: FormGroup) {
    const registrationInfo: NewVoter = {
      name: form['name'],
      role: form['role'],
      group: form['group'],
    };

    console.log(JSON.stringify(registrationInfo));
  }

  roleChange(tnsPickerIndex?) {
    if (!!tnsPickerIndex || tnsPickerIndex === 0) {
      this.registrationForm.get('role').setValue(tnsPickerIndex.toString());
    }

    this.dealerNotSelected =
      this.registrationForm.get('role').value === '0' ||
      this.registrationForm.get('role').value === '1';

    this.dealerNotSelected ?
      this.registrationForm.get('group').setValidators(Validators.required) :
      this.registrationForm.get('group').clearValidators();

    this.registrationForm.get('group').updateValueAndValidity();
  }
}
