import { BrowserModule, Title } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { WelcomePageComponent } from '@src/app/pages/welcome-page/welcome-page.component';
import { NavbarComponent } from '@src/app/components/navbar/navbar.component';
import { PageNotFoundComponent } from '@src/app/components/page-not-found/page-not-found.component';
import { RoomsPageComponent } from '@src/app/pages/rooms-page/rooms-page.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    WelcomePageComponent,
    NavbarComponent,
    PageNotFoundComponent,
    RoomsPageComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpClientModule,
  ],
  providers: [
    Title
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
